# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_tomcat', '0002_auto_20170301_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomcat_project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
