# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_tomcat', '0003_auto_20170301_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail_address', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('role', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tomcat_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tomcat_project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
