# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_tomcat', '0004_auto_20170301_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=10, null=True)),
                ('info', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tomcat_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.CharField(max_length=64)),
                ('project', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=8)),
                ('info', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tomcat_url',
            name='url',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
