# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_tomcat', '0005_auto_20170301_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomcat_project',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
